### PR TITLE
Fixes after Aaron's findings on ErrEnglish

### LINKED ISSUE #41: Improve ErrEnglish detection of read udp: connection refused error
Enhance ErrEnglish detection to accept an optional "read:" in middle of Golang error, eg:
```
read udp 104.236.65.170:38722->83.169.184.99:53: read: connection refused
                                                 ^^^^^^
```

Also, remove the "``Maybe nothing is listening on that port or a firewall is blocking.``" from the ErrEnglish.

### PR DESCRIPTION
**Pull request by coolparadox**
Fixes #41 #42 #43

### CODE REVIEW

File: utils/translate_error.go [hunk 1]
```diff
@@ -209,6 +211,20 @@ func translateCurlError(result *CurlResult) {
 			replacement = "DNS lookup timed out. Could not resolve $1 within " +
 				inIntegerSeconds(result.DialTime) +
 				" seconds."
+		} else if result.DNSTime <= dnsTimeout {
```
Comment (sajal) [inline utils/translate_error.go]: The `dnsTimeout` of DNS test is not applicable for curl test. 
https://pulse.turbobytes.com/results/5885796cecbe40377300f93c/  - This is a result where the DNS will always time out, and the timing ranges from 1.5 to 15 seconds.

Comment (coolparadox) [inline utils/translate_error.go]: The ``dnsTimeout`` threshold of this comparation is used to decide whether ErrEnglish is presented in a more concise format for Dial timeout errors in curl tests. The decision depends on the duration of DNS lookup phase, that of course can range from zero to 15 seconds.

Should I create a specific variable, say "``translateDnsThreshold``", and hardcode it to 5 seconds? Again, these are semantically the same information; it woudn't make sense to use a ``translateDnsThreshold`` different from ``dnsTimeout``.

**Comment by coolparadox** [comment]
@sajal please review
